# --- BorderPlugin Configuration ---

# Pre-generate all chunks within the border on server start (recommended for performance)
pregen_chunks: false
# How many chunks to pre-generate per server tick
pregen_chunks_per_tick: 10

border:
  # The current size (diameter) of the world border in blocks
  size: 1000
  # The X coordinate of the border center
  center_x: 0
  # The Z coordinate of the border center
  center_z: 0
  # How many blocks the border grows each time
  grow_amount: 100
  # At what time (24h format, e.g. 20:00) the border grows
  grow_time: "20:00"
  # On which days the border grows (use English day names, all caps)
  grow_days: ["MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY"]
  # Animate the border growth (smooth transition)
  grow_animated: true
  # Duration of the border growth animation in seconds
  grow_animated_seconds: 10
  # Send a chat broadcast message when the border grows
  broadcast: true
  # Log border changes to a file (border.log)
  log_to_file: true
  # Show a title message to all players when the border grows
  broadcast_title_enabled: true
  # Title fade-in time in ticks (20 ticks = 1 second)
  broadcast_title_fadein: 10
  # Title stay time in ticks
  broadcast_title_stay: 100
  # Title fade-out time in ticks
  broadcast_title_fadeout: 10
  # Play a sound to all players when the border grows
  sound_enabled: true
  # The Minecraft sound to play (see https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html)
  sound: "BLOCK_BEACON_ACTIVATE"
  # Sound volume (1.0 = normal)
  sound_volume: 1.0
  # Sound pitch (1.0 = normal)
  sound_pitch: 1.0
  # --- Shrink settings ---
  # Percentage chance (0-100) that the border will shrink instead of grow on a scheduled day
  shrink_chance_percent: 20
  # How many blocks the border shrinks when the chance triggers
  shrink_amount: 100
  # Send a chat message when the border shrinks
  shrink_broadcast: true
  # Play a sound to all players when the border shrinks
  shrink_sound_enabled: true
  # The Minecraft sound to play for shrinking
  shrink_sound: "ENTITY_ENDERMAN_TELEPORT"
  # Sound volume (1.0 = normal) for shrinking
  shrink_sound_volume: 1.0
  # Sound pitch (1.0 = normal) for shrinking
  shrink_sound_pitch: 1.0
  # --- Limits ---
  # The minimum border size in blocks; the border will never go below this value
  min_size: 16
