pregen_chunks: false
pregen_chunks_per_tick: 10
# BorderPlugin configuratie
border:
  size: 1000
  center_x: 0
  center_z: 0
  grow_amount: 100
  grow_time: "20:00"
  grow_days: ["MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY"]
  grow_animated: true
  grow_animated_seconds: 10
  broadcast: true
  log_to_file: true
  broadcast_message: "§a[Border] De wereldborder is vergroot naar %size% blokken!"
