
name: BorderPlugin
main: com.example.borderplugin.BorderPlugin
version: 1.0
description: Een plugin die de wereldborder automatisch vergroot.
author: JoeyNNL
api-version: 1.20
softdepend: [PlaceholderAPI]
commands:
  border:
    description: Border beheer commando
    usage: /border <reload|set|add|remove|center|info|help|bypass|log>
    permission: border.admin
    permission-message: Je hebt geen toegang tot dit commando.
