
name: AutoBorder
main: com.joeynnl.autoborder.AutoBorderPlugin
version: 1.1
description: Een plugin die de wereldborder automatisch vergroot.
author: JoeyNNL
api-version: 1.20
softdepend: ["PlaceholderAPI"]
commands:
  border:
    description: Border beheer commando
    usage: /border <reload|set|add|remove|center|info|help|bypass|log>
    permission: border.admin
    permission-message: Je hebt geen toegang tot dit commando.